### ISSUE TITLE
Permission to create new PR

### ISSUE THREAD

**Issue by santoshmohan** [jonwingfield/Faker.Net#9]
@jonwingfield: I have created new local branch to handle Australian State and postcode.

Can you please provide me permission to create Branch/Pull request?

**Comment by santoshmohan** [comment]
@mps @TimCollins @jonwingfield  : Can you please look in to this.

**Comment by jonwingfield** [comment]
You should have permission to send a pull request. Once you do, I'll review
it and merge it if everything looks OK.

**Comment by santoshmohan** [comment]
Thanks mate, but I am not able to create the branch and push my changes. Can you check if any permissions is required?

I get the below error : 
![image](https://cloud.githubusercontent.com/assets/6982545/11027212/267568fe-8707-11e5-8327-824ae72bf7ad.png)

![image](https://cloud.githubusercontent.com/assets/6982545/11027234/6cfecf04-8707-11e5-92a3-157b69d1cc19.png)

**Comment by jonwingfield** [comment]
@santashmohan, you have to first fork the repository, then push your changes and send a pull request. Github has a better explanation than I can give here: https://help.github.com/articles/using-pull-requests/
